steps:
  # アプリケーションのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/salesperson-backend:$COMMIT_SHA'
      - '.'
    id: 'build-app'

  # イメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/salesperson-backend:$COMMIT_SHA'
    id: 'push-image'
    waitFor: ['build-app']

  # Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'salesperson-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/salesperson-backend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:asia-northeast1:saleperson-app-db'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--service-account'
      - 'salesperson-backend-sa@$PROJECT_ID.iam.gserviceaccount.com'
    id: 'deploy'
    waitFor: ['push-image']

# タイムアウト設定
timeout: '1800s'

# ビルドされたイメージをArtifact Registryに保存
images:
  - 'gcr.io/$PROJECT_ID/salesperson-backend:$COMMIT_SHA'

# オプション設定
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
