steps:
  # アプリケーションのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/salesperson-backend', '.']

  # イメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/salesperson-backend']

  # Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'salesperson-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/salesperson-backend'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:asia-northeast1:saleperson-app-db'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@localhost:5432/saleperson-app-db?host=/cloudsql/$PROJECT_ID:asia-northeast1:saleperson-app-db'

images:
  - 'gcr.io/$PROJECT_ID/salesperson-backend'

substitutions:
  _DB_PASSWORD: Heisei50721  # 本番環境では Secret Managerを使用することを推奨 