steps:
  # 1. Docker イメージのビルド (linux/amd64 への明示的なビルド)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'gcr.io/saleperson-app/salesperson-backend:$COMMIT_SHA'
      - '.'
    id: 'build-app'

  # 2. イメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/saleperson-app/salesperson-backend:$COMMIT_SHA'
    id: 'push-image'
    waitFor: ['build-app']

  # 3. Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'salesperson-backend'
      - '--image'
      - 'gcr.io/saleperson-app/salesperson-backend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'saleperson-app:asia-northeast1:saleperson-app-db'
      - '--service-account'
      - 'salesperson-backend-sa@saleperson-app.iam.gserviceaccount.com'
      # Secret Managerからの環境変数設定
      - '--set-secrets'
      - 'DB_PASSWORD=db-password:latest,DB_USER=db-user:latest,NODE_ENV=node-env:latest,CLOUD_SQL_CONNECTION_NAME=cloud-sql-connection-name:latest,DB_NAME=db-name:latest,DATABASE_URL=database-url:latest,PROJECT_ID=project-id:latest'
    id: 'deploy'
    waitFor: ['push-image']

timeout: '1800s'

images:
  - 'gcr.io/saleperson-app/salesperson-backend:$COMMIT_SHA'

options:
  logging: 'CLOUD_LOGGING_ONLY'
  machineType: 'N1_HIGHCPU_8'
