steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--platform'
    - 'linux/amd64'
    - '-t'
    - 'gcr.io/saleperson-app/saleperson-backend:$COMMIT_SHA'
    - '.'
  id: 'build-app'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/saleperson-app/saleperson-backend:$COMMIT_SHA'
  id: 'push-image'
  waitFor: ['build-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'saleperson-backend'
    - '--image'
    - 'gcr.io/saleperson-app/saleperson-backend:$COMMIT_SHA'
    - '--region'
    - 'asia-northeast1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--add-cloudsql-instances'
    - 'saleperson-app:asia-northeast1:saleperson-app-db'
    - '--service-account'
    - 'saleperson-app-backend@saleperson-app.iam.gserviceaccount.com'
    - '--port'
    - '8080'
    - '--set-secrets'
    - 'DB_PASSWORD=db-password:latest,DB_USER=db-user:latest,NODE_ENV=node-env:latest,CLOUD_SQL_CONNECTION_NAME=cloud-sql-connection-name:latest,DB_NAME=db-name:latest,DATABASE_URL=database-url:latest,PROJECT_ID=project-id:latest'
  id: 'deploy'
  waitFor: ['push-image']

timeout: '1800s'

images:
  - 'gcr.io/saleperson-app/saleperson-backend:$COMMIT_SHA'
