version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@cloudsql:5432/${DB_NAME}
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - cloudsql

  cloudsql:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1
    command:
      - "--address=0.0.0.0"
      - "--port=5432"
      - "--credentials-file=/credentials.json"
      - "${CLOUD_SQL_CONNECTION_NAME}"
    volumes:
      - ./credentials.json:/credentials.json
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
