version: '3.8'

services:
  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1
    container_name: cloudsql-proxy
    volumes:
      - ./credentials.json:/config/credentials.json
    command:
      - "--credentials-file=/config/credentials.json"
      - "--address=0.0.0.0"
      - "--port=5432"
      - "${CLOUD_SQL_CONNECTION_NAME}"
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
  app:
    build: .
    container_name: app
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@cloudsql-proxy:5432/${DB_NAME}"
      PORT: 8080
      NODE_ENV: ${NODE_ENV}
      PROJECT_ID: ${PROJECT_ID}
      DB_NAME: ${DB_NAME}
      DIFY_API_KEY: ${DIFY_API_KEY}
      DIFY_BASE_URL: ${DIFY_BASE_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CLOUD_SQL_CONNECTION_NAME: ${CLOUD_SQL_CONNECTION_NAME}
    ports:
      - "3000:8080"
    depends_on:
      - cloudsql-proxy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  cloudsql:

