version: '3.8'

services:
  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1
    container_name: cloudsql-proxy
    volumes:
      - ./credentials.json:/config
      - ./cloudsql:/cloudsql
    command:
      - "--credentials-file=/config"
      - "--unix-socket=/cloudsql"
      - "saleperson-app:asia-northeast1:saleperson-app-db"
    networks:
      - app-network
    restart: unless-stopped

  app:
    build: .
    container_name: app
    environment:
      # host=/cloudsql/<CONNECTION_NAME> の形式を必ず指定する
      DATABASE_URL: "postgresql://postgres:Heisei50721@/saleperson-app-db?host=/cloudsql/saleperson-app:asia-northeast1:saleperson-app-db"
      PORT: 8080
      NODE_ENV: development
      PROJECT_ID: saleperson-app
      DB_NAME: saleperson-app-db
      DB_USER: postgres
      DB_PASSWORD: Heisei50721
      CLOUD_SQL_CONNECTION_NAME: saleperson-app:asia-northeast1:saleperson-app-db
    volumes:
      - ./cloudsql:/cloudsql
    ports:
      - "3000:8080"
    depends_on:
      - cloudsql-proxy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  cloudsql:
