version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:8080"  # ローカルの3000番ポートをコンテナの8080番ポートにマッピング
    environment:
      # Cloud SQL Proxy経由でのデータベース接続
      - DATABASE_URL=postgresql://postgres:Heisei50721@cloudsql:5432/saleperson-app-db
      - NODE_ENV=development
      - PORT=8080
      - PROJECT_ID=saleperson-app
      - DB_NAME=saleperson-app-db
      - CLOUD_SQL_CONNECTION_NAME=saleperson-app:asia-northeast1:saleperson-app-db
    networks:
      - app-network
    depends_on:
      - cloudsql

  cloudsql:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1
    command:
      - "--address=0.0.0.0"
      - "--port=5432"
      - "--credentials-file=/credentials.json"
      - "${CLOUD_SQL_CONNECTION_NAME}"
    volumes:
      - ./credentials.json:/credentials.json
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
