version: '3.8'

services:
  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1
    container_name: cloudsql-proxy
    volumes:
      - ./credentials.json:/config
    command:
      - "--credentials-file=/config"
      - "--port=5432"
      - "saleperson-app:asia-northeast1:saleperson-app-db"
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: app
    environment:
      DATABASE_URL: "postgresql://postgres:Heisei50721@127.0.0.1:5432/saleperson-app-db"
      PORT: 8080
      NODE_ENV: development
      PROJECT_ID: saleperson-app
      DB_NAME: saleperson-app-db
      DB_USER: postgres
      DB_PASSWORD: Heisei50721
      CLOUD_SQL_CONNECTION_NAME: saleperson-app:asia-northeast1:saleperson-app-db
    ports:
      - "3000:8080"
    depends_on:
      - cloudsql-proxy
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  cloudsql: